version: '3'
services:
  deployment-service:
    image: ghcr.io/eclipse-researchlabs/smartclide-deployment-service:master
    container_name: deployment-service
    hostname: deployment-service
    ports:
      - 3000:3000   
    environment:
      - GITLAB_URL=https://gitlab.dev.smartclide.eu/
      - MOM_HOST=rabbitmq
      - MOM_PORT=3332
      - MOM_USER=
      - MOM_PASSWORD=
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
    links:
      - rabbitmq:rabbitmq
      - mongo:mongo

  rabbitmq:
    image: "rabbitmq:latest"

  mongo:
    image: "mongo:4.4.14"
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
volumes:
  database-data: 